name: ohftokv5
description: OHF Partners brings you the best content in the best way.
publish_to: "none" # Remove this if you plan to publish to pub.dev.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Firebase packages
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.9
  firebase_app_check: ^0.2.1+8

  # State management & dependency injection
  provider: ^6.1.1
  shared_preferences: ^2.2.2

  # Environment variable management
  flutter_dotenv: ^5.1.0

  # Permissions
  permission_handler: ^11.3.0

  # Video optimization and caching
  cached_network_image: ^3.3.0
  flutter_cache_manager: ^3.3.1
  preload_page_view: ^0.2.0
  visibility_detector: ^0.4.0+2

  # Video player packages
  media_kit: ^1.1.10
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4
  video_player: ^2.8.2
  chewie: ^1.7.4

  # Network monitoring
  connectivity_plus: ^6.1.3
  http: ^1.1.0

  # Speech and AI
  speech_to_text: ^7.0.0
  langchain: ^0.7.7+2
  langchain_openai: ^0.7.3
  pinecone: ^0.7.2

  # Cloud Functions
  cloud_functions: ^4.5.8

  # Image picker
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env 